:sparkles:  Added support to storybook and some of it's addons
Otoru/Lugh pull request #8
Opened 2021-01-25 00:50 UTC by PedroPretto

Foi adicionado o storybook ao projeto, assim os contribuintes do repositório podem trabalhar em componentes isolados sem muitos problemas para testar :)

Para iniciar o storybook basta digitar no console
`
yarn storybook
`

A arquitetura do playbook envolve o diretório .storybook e o src/stories, onde no primeiro se declara que tipo de arquivos a aplicação deverá monitorar e seus addons, enquanto no segundo estarão armazenados nossos stories.

Então, supondo que o projeto tenha um componente button implementado, o mesmo deve ser declarado da seguinte maneira como um `/src/stories/Buttons.stories.tsx`:

```
import React from 'react';
import { Button } from '../components/atoms/index';

const title = {
  title: 'Buttons',
};

const logger = () => {
  console.log('TESTE');
};

export const PrimaryButton: React.VFC = () => {
  return <Button onClick={() => logger()} text="Button" />;
};

export default title;
```

Onde é exportado por default o nome da categoria de stories, logo uma categoria pode ter mais de um stories em um mesmo arquivo, contanto que siga o componente definido (e.g: multiplos estados de um botão).

Addons adicionados foram:

- knobs: Permite alterar o estado dos componentes em tempo real
- storysource: Permite visualizar a implementação dos componentes

Alguns outros componentes como viewport e docs já estão incluídos no _essentials_ pré instalado com o storybook.

2021-01-25 11:43 UTC, Otoru requested changes

2021-01-25 11:43 UTC, Otoru commented on tsconfig.json
> -    "jsx": "react-jsx"
Essa mudança é desnecessária. Para solucionar esse erro você deve instalar todas as dependências e na sequência selecionar a versão correta do typescript para o vscode. Podemos fazer essa alteração em par caso queira.

2021-01-25 16:12 UTC, Otoru requested changes

2021-01-25 16:12 UTC, Otoru commented on tsconfig.json
> +    "jsx": "react"
Essa mudança é desnecessária. Para solucionar esse erro você deve instalar todas as dependências e na sequência selecionar a versão correta do typescript para o vscode. Podemos fazer essa alteração em par caso queira.

2021-01-25 16:18 UTC, PedroPretto commented on tsconfig.json
> +    "jsx": "react"
Perfeito, podemos fazer essa alteração em par sim.

2021-01-27 22:57 UTC, Otoru approved these changes

2021-01-27 22:58 UTC, merged